"""Before/after of every fix-loop round on the CURRENT code: each fix is switched off ("before") and on ("after")
in the same run, so no old branch or commit is needed (fix/DECLARATION.md). Writes fix/results/fix<N>.md.

    python fix/reproduce.py 1     # depth-scale correction, 3 captures of room 421337 vs the Faro laser (~2 min)
    python fix/reproduce.py 2     # Mondrian wall-length bins, LiDAR calibration records (seconds)
    python fix/reproduce.py 3     # conformal calibration for video/photo, calibration records (seconds)
    python fix/reproduce.py 4     # floor-boundary notch merge, LiDAR benchmark captures (~5 min)
    python fix/reproduce.py all

Fixes 2 and 3 need the calibration records (python bench/calibrate.py --tier lidar|video|photo). The numbers are
the current pipeline with one fix removed; the declaration's own before-numbers were measured at the time.
"""
from __future__ import annotations

import json
import subprocess
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(ROOT / "bench"))
OUT = ROOT / "fix" / "results"
RUNS = ROOT / "out" / "fix"


def _write(n: int, lines: list[str]):
    OUT.mkdir(parents=True, exist_ok=True)
    (OUT / f"fix{n}.md").write_text("\n".join(lines) + "\n")
    print("\n".join(lines))


def fix1():
    subprocess.run([sys.executable, str(ROOT / "bench" / "fix_loop.py")], check=True, cwd=ROOT)
    _write(1, ["# Fix 1: LiDAR depth-scale correction", "",
               "Regenerated by `python bench/fix_loop.py` (before = depth as recorded, after = held-out scale).", "",
               *(ROOT / "fix" / "before_after.md").read_text().splitlines()])


def _fit_rows(recs: list[dict], tier: str, kinds: list[str]):
    from roomscope.core import calibrate as C
    f = C.fit(recs)[tier]
    rows = []
    for k in kinds:
        v = f.get(k)
        if v:
            hw = v["loro_median_halfwidth"]
            sc = v["loro_interval_score"]
            cov = v["loro_coverage"]
            rows.append(f"| {k} | {v['n']} | {v['raw_coverage']:.2f} | {'-' if cov is None else f'{cov:.2f}'} | "
                        f"{'-' if hw is None else f'{100 * hw:.2f} cm'} | {'-' if sc is None else f'{100 * sc:.2f} cm'} |")
    return rows


HDR = ["| quantity | n | raw coverage | calibrated coverage (leave-one-room-out) | median half-width | interval score |",
       "|---|---|---|---|---|---|"]


def fix2():
    from calibrate import add_bins
    recs = add_bins(json.loads((ROOT / "out/calib/records_lidar.json").read_text()), "lidar")
    before = [{k: v for k, v in r.items() if k != "bin"} for r in recs]
    _write(2, ["# Fix 2: Mondrian bins for LiDAR wall lengths", "",
               "Same calibration records; before = one wall-length quantile, after = one per bin "
               "(corner-supported / inferred).", "", "**Before**", "", *HDR,
               *_fit_rows(before, "lidar", ["wall_length"]), "", "**After**", "", *HDR,
               *_fit_rows(recs, "lidar", ["wall_length:supported", "wall_length:inferred"])])


def fix3():
    lines = ["# Fix 3: conformal calibration for the video and photo tiers", "",
             "Same calibration records; before = raw plane-fit intervals (raw coverage), after = conformal "
             "intervals scored leave-one-room-out.", "", *HDR]
    for tier in ("video", "photo"):
        recs = json.loads((ROOT / f"out/calib/records_{tier}.json").read_text())
        lines += [r.replace("| ", f"| {tier} ", 1) for r in _fit_rows(recs, tier, ["ceiling_height", "wall_length"])]
    _write(3, lines)


def fix4():
    import yaml
    from repeatability import compare
    from roomscope.core import layout as L
    from roomscope.pipeline import run_capture
    caps = [e for e in yaml.safe_load((ROOT / "bench/set.yaml").read_text())["captures"]
            if e["id"] in ("42444946", "42444949", "honka_long", "honka_short")]
    for tag, on in (("before", False), ("after", True)):
        L.NOTCH_MERGE = on
        for e in caps:
            d = RUNS / "fix4" / tag / e["id"]
            if not list(d.glob("*/result.json")):
                run_capture(ROOT / e["path"], "lidar", d, damage=False)
    lines = ["# Fix 4: floor-boundary notches merged, not reported as walls", "",
             "LiDAR benchmark pairs; before = notch merge off, after = on. A wall pair agrees when the two lengths "
             "are within max(1 cm, 0.5 %).", "",
             "| pair | before: within / matched | before: floor-boundary edges | after: within / matched | "
             "after: floor-boundary edges |", "|---|---|---|---|---|"]
    for a, b in (("42444946", "42444949"), ("honka_long", "honka_short")):
        cells = []
        for tag in ("before", "after"):
            da = next((RUNS / "fix4" / tag / a).glob("*/result.json")).parent
            db = next((RUNS / "fix4" / tag / b).glob("*/result.json")).parent
            ws = [w for m in compare(da, db).get("matched_rooms", []) for w in m.get("walls", [])]
            ok = sum(abs(w["diff"]) <= max(0.01, 0.005 * abs(w["a"])) for w in ws)
            fb = sum("floor boundary" in w for d in (da, db) for w in json.loads((d / "result.json").read_text())["warnings"])
            cells += [f"{ok} / {len(ws)}", str(fb)]
        lines.append(f"| {a} / {b} | " + " | ".join(cells) + " |")
    _write(4, lines)


if __name__ == "__main__":
    which = sys.argv[1] if len(sys.argv) > 1 else "all"
    for n, f in ((1, fix1), (2, fix2), (3, fix3), (4, fix4)):
        if which in ("all", str(n)):
            f()
